export const IMAGE_BASE_URL = 'https://image.tmdb.org/t/p'

export const GET_POPULAR_REQUEST = 'GET_POPULAR_REQUEST'
export const GET_POPULAR_SUCCESS = 'GET_POPULAR_SUCCESS'

export const GET_TOP_RATED_REQUEST = 'GET_TOP_RATED_REQUEST'
export const GET_TOP_RATED_SUCCESS = 'GET_TOP_RATED_SUCCESS'

export const GET_MOVIE_REQUEST = 'GET_MOVIE_REQUEST'
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS'

export const GET_DETAIL_REQUEST = 'GET_DETAIL_REQUEST'
export const GET_TV_DETAIL_REQUEST = 'GET_TV_DETAIL_REQUEST'
export const GET_DETAIL_SUCCESS = 'GET_DETAIL_SUCCESS'
export const CLEAR_DETAIL = 'CLEAR_DETAIL'

export const DISCOVER_SUCCESS = 'DISCOVER_SUCCESS'
export const DISCOVER_TV_SUCCESS = 'DISCOVER_TV_SUCCESS'
export const DISCOVER_REQUEST = 'DISCOVER_REQUEST'

export const OPTIONS_REQUEST = 'OPTIONS_REQUEST'
export const OPTIONS_SUCCESS = 'OPTIONS_SUCCESS'

export const LOAD_MORE_REQUEST = 'LOAD_MORE_REQUEST'

export const LOAD_MORE_TV_SUCCESS = 'LOAD_MORE_TV_SUCCESS'
export const LOAD_MORE_MOVIE_SUCCESS = 'LOAD_MORE_MOVIE_SUCCESS'

export const RESET_PAGE = 'RESET_PAGE'
export const RESET_LIST = 'RESET_LIST'
export const SET_PAGE = 'SET_PAGE'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_ERROR = 'AUTH_ERROR'

export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS'
export const ADD_FAVORITE_REQUEST = 'ADD_FAVORITE_REQUEST'
export const ADD_FAVORITE_ERROR = 'ADD_FAVORITE_ERROR'

export const GET_FAVORITES_SUCCESS = 'GET_FAVORITES_SUCCESS'
export const GET_FAVORITES_REQUEST = 'GET_FAVORITES_REQUEST'
export const GET_FAVORITES_ERROR = 'GET_FAVORITES_ERROR'
