export const IMAGE_BASE_URL = 'https://image.tmdb.org/t/p'

export const GET_POPULAR_REQUEST = 'GET_POPULAR_REQUEST'
export const GET_POPULAR_SUCCESS = 'GET_POPULAR_SUCCESS'

export const GET_TOP_RATED_REQUEST = 'GET_TOP_RATED_REQUEST'
export const GET_TOP_RATED_SUCCESS = 'GET_TOP_RATED_SUCCESS'

export const GET_MOVIE_REQUEST = 'GET_MOVIE_REQUEST'
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS'
